routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\GeneralInformationsController;
use App\Http\Controllers\EducationsController;
use App\Http\Controllers\ProfessionalSkillsController;
use App\Http\Controllers\ProfessionalHistoriesController;
use App\Http\Controllers\RecentProjectsController;
use App\Http\Controllers\ProfessionalDetailsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('general_information', GeneralInformationsController::class);
Route::resource('educations', EducationsController::class);
Route::resource('professional_histories', ProfessionalHistoriesController::class);
Route::resource('recent_projects', RecentProjectsController::class);
Route::resource('professional_details', ProfessionalDetailsController::class);



Route::resource('skills', ProfessionalSkillsController::class);

resources/views/backend/educations.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid py-5">
    <div class="row justify-content-center">
        <div class=" col-lg-2 col-md-2 col-2">

        </div>
        <div class="col-lg-6 col-md-8 col-8">
            <h3 class="py-3"><strong>Education Details</strong></h3>

            <form method="POST" enctype="multipart/form-data" action="{{route('educations.store')}}">
                @csrf
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif

                <div class="row form-group">
                    <div class="col">
                      <input type="text" id="name_of_degree" class="form-control @error('name_of_degree') is-invalid @enderror" name="name_of_degree" placeholder="Enter your degree" value="{{ old('name_of_degree') }}">
                        @error('name_of_degree')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                    <div class="col">
                        <input type="text" class="form-control @error('educational_institution_name') is-invalid @enderror" name="educational_institution_name" placeholder="Enter educational institutional name" value={{old('educational_institution_name')}}>
                        @error('educational_institution_name')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                        <input type="text" onfocus="(this.type='date')" class="form-control @error('starting_date') is-invalid @enderror" name="starting_date" placeholder="Starting Date" value={{old('starting_date')}}>
                        @error('starting_date')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                    <div class="col">
                      <input type="text" onfocus="(this.type='date')" id="ending_date" class="form-control @error('ending_date') is-invalid @enderror" name="ending_date" placeholder="Ending Date" value="{{ old('ending_date') }}">
                        @error('ending_date')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                      <input type="file" id="institution_logo" class="form-control @error('institution_logo') is-invalid @enderror" name="institution_logo" placeholder="Institutional Logo" value="{{ old('institution_logo') }}">
                        @error('institution_logo')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group justify-content-center">
                    <div class="col-lg-12 col-md-12 col-12 text-center">
                      <button class="dashboard-button btn col-lg-4" type="submit">Add</button>
                    </div>

                </div>
                

            </form>
        </div>

        <div class="col-lg-4 col-md-3 col-3 py-3 text-center border-left">
            <h3 class="py-3"><strong>Education Information</strong></h3>
            @foreach($education_data ?? '' as $data)
            <div class="container-fluid">
                <div class="row py-3 mb-2 education_details">
                    <div class="col-lg-2 col-md-2 col-2">
                        <img src="/images/{{ $data->institution_logo }}" alt="" class="img-fluid">
                    </div>
                    <div class="col-lg-8 col-md-8 col-8">
                        <p class="strong"><strong>{{ $data->educational_institution_name }}</strong></p>
                        <p>{{ $data->name_of_degree }}</p>
                        <p>{{ $data->starting_date }} - {{ $data->ending_date }}</p>
                        

                    </div>
                    <div class="col-lg-1 col-md-1 col-1">
                        <i class="fab fa-laravel"></i>
                        <i class="fab fa-laravel"></i>
                    </div>
                </div>
            </div>
                
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/backend/professional_details.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid py-5">
    <div class="row justify-content-center">
        <div class=" col-lg-2 col-md-2 col-2">

        </div>
        <div class="col-lg-5 col-md-5 col-5 dashboard_box">
            <h3 class="py-3"><strong>Professional Details</strong></h3>

            <form method="POST" enctype="multipart/form-data" action="{{route('professional_details.store')}}">
                @csrf
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif

                <div class="row form-group">
                    <div class="col">
                        <textarea class="form-control border-bottom @error('professional_summary') is-invalid @enderror" id="professional_summary" name="professional_summary" rows="4" placeholder="Professional Summary">{{old('professional_summary')}}</textarea>
                        @error('professional_summary')
                        <div class="alert"> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                      <input type="text" id="professional_title" class="form-control @error('professional_title') is-invalid @enderror" name="professional_title" placeholder="Enter your professional title" value="{{ old('professional_title') }}">
                        @error('professional_title')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group justify-content-center">
                    <div class="col-lg-12 col-md-12 col-12 text-center">
                      <button class="dashboard-button btn col-lg-4" type="submit">Add</button>
                    </div>

                </div>
                

            </form>
        </div>

        <div class="col-lg-5 col-md-5 col-5 py-3">
            <h3 class="py-3"><strong>Skills</strong></h3>
            <form method="POST" enctype="multipart/form-data" action="{{route('skills.store')}}">
                @csrf
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif

                <div class="row form-group">
                    <div class="col">
                      <input type="text" id="skill_name" class="form-control @error('skill_name') is-invalid @enderror" name="skill_name" placeholder="Enter your skill" value="{{ old('skill_name') }}">
                        @error('skill_name')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                      <input type="text" id="skill_icon" class="form-control my icon-picker @error('skill_icon') is-invalid @enderror" name="skill_icon" placeholder="Enter your skill icon" value="{{ old('skill_icon') }}">
                        @error('skill_icon')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                        <select class="form-control @error('skill_category') is-invalid @enderror" id="skill_category" name="skill_category" >
                            <option selected value="">Choose a skill category</option>
                            <option value="0">Professional Skill</option>
                            <option value="1">Interpersonel Skill</option>
                            </select>
    
                            @error('skill_category')
                                <div class="alert"> {{$messaskill_categoryge}}</div>
                            @enderror
                    </div>

                </div>

                <div class="row form-group justify-content-center">
                    <div class="col-lg-12 col-md-12 col-12 text-center">
                      <button class="dashboard-button btn col-lg-4" type="submit">Add</button>
                    </div>

                </div>
                

            </form>
        </div>
    </div>
</div>
@endsection

resources/views/backend/professional_histories.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid py-5">
    <div class="row justify-content-center">
        <div class=" col-lg-2 col-md-2 col-2">

        </div>
        <div class="col-lg-6 col-md-8 col-8">
            <h3 class="py-3"><strong>Work History</strong></h3>

            <form method="POST" action="{{route('professional_histories.store')}}">
                @csrf
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif
                <div class="row form-group">
                    <div class="col">
                      <input type="text" id="job_title" class="form-control @error('job_title') is-invalid @enderror" name="job_title" placeholder="Enter your job title" value="{{ old('job_title') }}">

                      @error('job_title')
                        <div class="alert"> {{$message}}</div>
                      @enderror

                    </div>
                    <div class="col">
                        <select class="form-control @error('job_type') is-invalid @enderror" id="job_type" name="job_type" >
                        <option selected value="">Choose a job type</option>
                        <option value="Full Time">Full Time</option>
                        <option value="Part Time">Part Time</option>
                        <option value="Casual">Casual</option>
                        <option value="Contract">Contract</option>
                        <option value="Internship">Internship</option>
                        </select>

                        @error('job_type')
                            <div class="alert"> {{$message}}</div>
                        @enderror

                    </div>
                    
                    
                </div>

                <div class="row form-group">
                    <div class="col">
                        <input type="text" id="organisation_name" class="form-control @error('organisation_name') is-invalid @enderror" name="organisation_name" placeholder="Enter organization name" value={{old('organisation_name')}}>
                          @error('organisation_name')
                              <div class="alert"> {{$message}}</div>
                          @enderror
                      </div>
                      <div class="col">
                        <input type="text" id="organisation_location" class="form-control @error('organisation_location') is-invalid @enderror" name="organisation_location" placeholder="Enter organization location" value="{{ old('organisation_location') }}">
  
                          @error('organisation_location')
                              <div class="alert"> {{$message}}</div>
                          @enderror
  
                    </div>
                    
                    
                </div>

                <div class="form-group">
                    <textarea id="roles_responsibilities" class="form-control border-bottom @error('roles_responsibilities') is-invalid @enderror" name="roles_responsibilities" rows="3" placeholder="Enter your job roles and responsibilities">{{old('roles_responsibilities')}}</textarea>

                    @error('roles_responsibilities')
                        <div class="alert"> {{$message}}</div>
                    @enderror

                </div>

                <div class="row form-group">
                    <div class="col">
                        <label for="current_job"><strong>I am currently involved with this role.</strong>  </label>
                    </div>
                    <div class="col">
                        <input class="form-check-input" type="checkbox" id="current_job" name="current_job" value=1>
                    </div>

                </div>

                <div class="row form-group">
                    <div class="col">
                        <label for="current_job">Starting Date: </label>
                        <input type="date" id="starting_date" class="form-control @error('starting_date') is-invalid @enderror" name="starting_date" placeholder="Enter starting date" value="{{ old('starting_date') }}">

                        @error('starting_date')
                            <div class="alert"> {{$message}}</div>
                        @enderror

                    </div>
                    <div class="col" id="end_date">
                        <label for="current_job">End Date: </label>
                        <input type="date" id="ending_date" class="form-control @error('ending_date') is-invalid @enderror" name="ending_date" placeholder="Enter end date" value={{old('ending_date')}}>

                        @error('ending_date')
                            <div class="alert"> {{$message}}</div>
                        @enderror

                    </div>
                </div>

                <div class="row form-group py-3">
                    <div class="col">
                        <button class="btn dashboard-button col-lg-4" type="submit">Add Work</button>
                    </div>
                </div>

            </form>

        </div>

        <div class="col-lg-3 col-md-2 col-2 py-3 border-left">

            <h3 class="py-3"><strong>Work Experience</strong></h3>
            @foreach($professionalHistories_data ?? '' as $data)
            <div class="accordion" id="accordionExample{{$data->id}}">
                
                <div class="card border-white">
                  <div class="card-header" id="headingOne{{$data->id}}">
                    <h2 class="mb-0">
                      <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne{{$data->id}}" aria-expanded="true" aria-controls="collapseOne{{$data->id}}">
                        <div class="col-lg-12">
                            {{ $data->organisation_name}} AS
                        </div>
                        <div class="col-lg-12">
                            {{ $data->job_title}}
                        </div>
                      </button>
                    </h2>
                  </div>

                  <div id="collapseOne{{$data->id}}" class="collapse" aria-labelledby="headingOne{{$data->id}}" data-parent="#accordionExample{{$data->id}}">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-3 bg-danger my-auto">
                                <p class="my-4">3 Mon</p>

                            </div>
                            <div class="col-lg-9 col-md-12 col-12">
                                <p>{{ $data->starting_date }} - 
                                    @if($data->ending_date == NULL)
                                        CURRENT
                                    @else
                                        {{ $data->ending_date }}
                                    @endif
                                </p>
                            </div>
                            <div class="col-lg-12 col-md-12 col-12 mx-auto my-2">
                                <p>
                                    {{$data->roles_responsibilities}}
                                </p>
                            </div>
                        </div>
                    </div>
                  </div>
                </div>
                

              </div>
              @endforeach
        </div>
</div>
@endsection

resources/views/backend/recent_projects.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid py-5">
    <div class="row justify-content-center">
        <div class=" col-lg-2 col-md-2 col-2">

        </div>
        <div class="col-lg-6 col-md-8 col-8">
            <h3 class="py-3"><strong>Project Information</strong></h3>

            <form method="POST" enctype="multipart/form-data" action="{{route('recent_projects.store')}}">
                @csrf
                @if(session()->has('success'))
                    <div class="alert alert-success">
                        {{ session()->get('success') }}
                    </div>
                @endif

                <div class="row form-group">
                    <div class="col">
                      <input type="text" id="project_title" class="form-control @error('project_title') is-invalid @enderror" name="project_title" placeholder="Enter your project title" value="{{ old('project_title') }}">
                        @error('project_title')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                        <input type="text" onfocus="(this.type='file')" id="project_snapshot" class="form-control @error('project_snapshot') is-invalid @enderror" name="project_snapshot" placeholder="Project Snapshot" value="{{ old('project_snapshot') }}">
                        @error('project_snapshot')
                        <div class="alert "> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col">
                        <textarea class="form-control border-bottom @error('project_description') is-invalid @enderror" id="project_description" name="project_description" rows="3" placeholder="Project Description">{{old('project_description')}}</textarea>
                        @error('project_description')
                        <div class="alert"> {{$message}}</div>
                        @enderror
                    </div>
                </div>

                <div class="row form-group justify-content-center">
                    <div class="col-lg-12 col-md-12 col-12 text-center">
                      <button class="dashboard-button btn col-lg-4" type="submit">Add</button>
                    </div>

                </div>
                

            </form>
        </div>

        <div class="col-lg-4 col-md-3 col-3 py-3 text-center border-left">
            <h3 class="py-3"><strong>Education Information</strong></h3>
            @foreach($recentProjects ?? '' as $data)
            <div class="container-fluid">
                <div class="row">
                    <img src="/images/projects/{{$data->project_snapshot}}" alt="" class="img-fluid">
                </div>
            </div>
                
            @endforeach
        </div>
    </div>
</div>
@endsection